### ISSUE TITLE
Updates to the Hcal reconstrucion

### ISSUE THREAD

**Issue by cmantill** [LDMX-Software/Hcal#40]
## Goals

- [ ] Update waveform (pulse)
- [ ] Update amplitude correction (Ampl[t-1]/Ampl[t])
- [ ] Update TOA timewalk correction
- [ ] Add TOT reconstruction
- [ ] Load conditions and verify reconstruction by ID. See issue [34](https://github.com/LDMX-Software/Hcal/issues/34).
- [ ] Make sure that all digis are processed. Currently the code assumes that digis are ordered. See issue [1067](https://github.com/LDMX-Software/ldmx-sw/issues/1067).
- [ ] Modify the position measurement for measurements carried out w the horizontal bars shifted. See issue [37](https://github.com/LDMX-Software/Hcal/issues/37).

**Comment by tomeichlersmith** [comment]
Working on add TOT recon with #44
